<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PrivateType</AssemblyName>
    <RootNamespace>PrivateType.Launcher</RootNamespace>
    <ApplicationIcon>..\PrivateType.App\Assets\PrivateType.ready.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
