<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\PrivateType.ready.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
      <AssemblyName>PrivateType</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PrivateType.Core\PrivateType.Core.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\PrivateType.ready.ico" />
    <Resource Include="Assets\PrivateType.listening.ico" />
  </ItemGroup>
</Project>
